import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts'
import './styles.css'
import { initialTheme, saveTheme } from './theme.js'

const zonedParts = (date,timeZone) => Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]))
const inTimeZone = (date,timeZone) => {const p=zonedParts(date,timeZone);return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`}
const zonedDateTimeToIso = (value,timeZone) => {const [date,time]=value.split('T'),[year,month,day]=date.split('-').map(Number),[hour,minute]=time.split(':').map(Number);const desired=Date.UTC(year,month-1,day,hour,minute);let utc=desired;for(let i=0;i<3;i++){const p=zonedParts(new Date(utc),timeZone);const represented=Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day),Number(p.hour),Number(p.minute));utc-=represented-desired}if(inTimeZone(new Date(utc),timeZone)!==value)throw new Error(`The selected time does not exist in ${timeZone}.`);return new Date(utc).toISOString()}
const blank = (timeZone='UTC') => ({charged_at:inTimeZone(new Date(),timeZone),odometer_km:'',soc_before:'',soc_after:'',kwh_charged:'',amount_paid:'',connector_type:'',provider:'',location:'',notes:''})

function chargeToForm(c,timeZone) {
  return {charged_at:inTimeZone(new Date(c.charged_at),timeZone),odometer_km:Math.round(c.odometer_km).toString(),soc_before:c.soc_before.toString(),soc_after:c.soc_after.toString(),kwh_charged:c.kwh_charged.toString(),amount_paid:c.amount_paid.toString(),connector_type:c.connector_type??'',provider:c.provider??'',location:c.location??'',notes:c.notes??''}
}

async function api(path, options={}) {
  const res=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options})
  if(!res.ok) throw new Error((await res.text())||`HTTP ${res.status}`)
  return res.status===204?null:res.json()
}

function App(){
  const [theme,setTheme]=useState(initialTheme)
  const [editOrigin,setEditOrigin]=useState('records')
  useEffect(()=>{document.documentElement.dataset.theme=theme},[theme])
  const toggleTheme=()=>{const next=theme==='dark'?'light':'dark';setTheme(next);saveTheme(next)}
  const [charges,setCharges]=useState([]),[providers,setProviders]=useState([])
  const [settings,setSettings]=useState({vehicle_name:'My EV',usable_battery_kwh:60,maximum_range_km:400,currency:'USD'})
  const [version,setVersion]=useState({version:'1.4.3',build_sha:'unknown',database:'unknown',timezone:'UTC'})
  const [form,setForm]=useState(blank()),[tab,setTab]=useState('dashboard'),[error,setError]=useState(''),[editingId,setEditingId]=useState(null)
  const [settingsMessage,setSettingsMessage]=useState(''),[newProvider,setNewProvider]=useState('')
  const [dashboardPeriod,setDashboardPeriod]=useState('all'),[selectedMonth,setSelectedMonth]=useState(''),[selectedYear,setSelectedYear]=useState(''),[customStartDate,setCustomStartDate]=useState(''),[customEndDate,setCustomEndDate]=useState('')

  const load=async()=>{try{const[c,s,p,v]=await Promise.all([api('/api/charges'),api('/api/settings'),api('/api/providers'),api('/api/version')]);setCharges(c);setSettings(s);setProviders(p);setVersion(v);setForm(current=>editingId||current.odometer_km?current:{...current,charged_at:inTimeZone(new Date(),v.timezone)})}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[])

  const locationSuggestions=useMemo(()=>[...new Set(charges.map(x=>x.location?.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[charges])
  const availableMonths=useMemo(()=>[...new Set(charges.map(x=>inTimeZone(new Date(x.charged_at),version.timezone).slice(0,7)))].sort().reverse(),[charges,version.timezone])
  const availableYears=useMemo(()=>[...new Set(charges.map(x=>inTimeZone(new Date(x.charged_at),version.timezone).slice(0,4)))].sort((a,b)=>Number(b)-Number(a)),[charges,version.timezone])
  useEffect(()=>{if(!selectedMonth&&availableMonths.length)setSelectedMonth(availableMonths[0]);if(!selectedYear&&availableYears.length)setSelectedYear(availableYears[0])},[availableMonths,availableYears,selectedMonth,selectedYear])

  const filteredCharges=useMemo(()=>charges.filter(c=>{if(dashboardPeriod==='all')return true;const local=inTimeZone(new Date(c.charged_at),version.timezone),date=local.slice(0,10);if(dashboardPeriod==='month')return local.slice(0,7)===selectedMonth;if(dashboardPeriod==='year')return local.slice(0,4)===selectedYear;if(dashboardPeriod==='custom')return (!customStartDate||date>=customStartDate)&&(!customEndDate||date<=customEndDate);return true}),[charges,dashboardPeriod,selectedMonth,selectedYear,customStartDate,customEndDate,version.timezone])

  const stats=useMemo(()=>{const valid=filteredCharges.filter(x=>x.efficiency_km_per_kwh);const distance=valid.reduce((a,x)=>a+x.distance_km,0);const used=valid.reduce((a,x)=>a+x.estimated_energy_used_kwh,0);const cost=filteredCharges.reduce((a,x)=>a+x.amount_paid,0);const charged=filteredCharges.reduce((a,x)=>a+x.kwh_charged,0);const breakdown={AC:{energy:0,cost:0},DC:{energy:0,cost:0}};filteredCharges.forEach(x=>{if(x.connector_type&&breakdown[x.connector_type]){breakdown[x.connector_type].energy+=x.kwh_charged;breakdown[x.connector_type].cost+=x.amount_paid}});return{efficiency:used?distance/used:null,distance,cost,costPerKm:distance?cost/distance:null,charged,avgCost:charged?cost/charged:null,breakdown}},[filteredCharges])
  const chart=[...filteredCharges].filter(x=>x.efficiency_km_per_kwh).reverse().map(x=>({odometer:Math.round(x.odometer_km),efficiency:Number(x.efficiency_km_per_kwh.toFixed(2))}))

  const submit=async e=>{e.preventDefault();setError('');const before=Number(form.soc_before),after=Number(form.soc_after);if(before<0||before>100||after<0||after>100)return setError('SOC must be between 0 and 100.');if(!Number.isInteger(Number(form.odometer_km)))return setError('Odometer must be a whole number.');let chargedAt;try{chargedAt=zonedDateTimeToIso(form.charged_at,version.timezone)}catch(e){return setError(e.message)}const payload={...form,charged_at:chargedAt,odometer_km:Number(form.odometer_km),soc_before:before,soc_after:after,kwh_charged:Number(form.kwh_charged),amount_paid:Number(form.amount_paid),connector_type:form.connector_type||null,provider:form.provider||null,location:form.location.trim()||null,notes:form.notes.trim()||null};try{await api(editingId?`/api/charges/${editingId}`:'/api/charges',{method:editingId?'PUT':'POST',body:JSON.stringify(payload)});setForm(blank(version.timezone));setEditingId(null);await load();setTab(editingId?editOrigin:'dashboard')}catch(e){setError(e.message)}}
  const startEdit=c=>{setEditOrigin(tab);setForm(chargeToForm(c,version.timezone));setEditingId(c.id);setTab('add');window.scrollTo({top:0,behavior:'smooth'})}
  const cancelEdit=()=>{if(editingId)setTab(editOrigin);setEditingId(null);setForm(blank(version.timezone));setError('')}
  const deleteCharge=async id=>{if(!confirm('Delete this charging record?'))return;try{await api(`/api/charges/${id}`,{method:'DELETE'});await load()}catch(e){setError(e.message)}}
  const saveSettings=async e=>{e.preventDefault();setError('');const capacity=Number(settings.usable_battery_kwh);if(capacity<=10||capacity>300)return setError('Usable battery capacity must be greater than 10 kWh and no more than 300 kWh.');try{await api('/api/settings',{method:'PUT',body:JSON.stringify({...settings,usable_battery_kwh:capacity,maximum_range_km:Number(settings.maximum_range_km)})});setSettingsMessage('Settings saved successfully.');setTimeout(()=>setSettingsMessage(''),3000);await load()}catch(e){setError(e.message)}}
  const addProvider=async()=>{if(!newProvider.trim())return;try{await api('/api/providers',{method:'POST',body:JSON.stringify({name:newProvider.trim()})});setNewProvider('');await load()}catch(e){setError(e.message)}}
  const editProvider=async p=>{const name=prompt('Charging provider name',p.name);if(!name||name.trim()===p.name)return;try{await api(`/api/providers/${p.id}`,{method:'PUT',body:JSON.stringify({name:name.trim()})});await load()}catch(e){setError(e.message)}}
  const removeProvider=async p=>{if(!confirm(`Remove ${p.name} from the provider list? Historical records will be kept.`))return;try{await api(`/api/providers/${p.id}`,{method:'DELETE'});await load()}catch(e){setError(e.message)}}

  return <div className="app">
    <header><div><h1>⚡ EV Efficiency</h1><div className="subtitle">{settings.vehicle_name}</div></div><nav>{[['dashboard','Dashboard'],['add','+ Charging'],['records','Records'],['settings','Settings']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>{if(k==='add'&&tab!=='add')cancelEdit();setTab(k)}}>{l}</button>)}</nav><button className="theme-toggle" type="button" role="switch" aria-label="Dark mode" aria-checked={theme==='dark'} onClick={toggleTheme}>{theme==='dark'?'Dark mode':'Light mode'}</button></header>
    {error&&<div className="error">{error}</div>}
    {tab==='dashboard'&&<><section className="panel dashboard-filter-panel"><div className="filter-header"><div><h2>Dashboard period</h2><p className="muted filter-description">Filter dashboard metrics and charging breakdown.</p></div><div className="record-count">{filteredCharges.length} record{filteredCharges.length===1?'':'s'}</div></div><div className="period-slicer">{[['all','All Time'],['month','By Month'],['year','By Year'],['custom','Custom Date Range']].map(([k,l])=><button key={k} className={dashboardPeriod===k?'active':''} onClick={()=>setDashboardPeriod(k)}>{l}</button>)}</div>{dashboardPeriod==='month'&&<div className="filter-controls"><Field label="Month"><select value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)}>{availableMonths.map(m=>{const[y,n]=m.split('-').map(Number);return <option key={m} value={m}>{new Date(y,n-1,1).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</option>})}</select></Field></div>}{dashboardPeriod==='year'&&<div className="filter-controls"><Field label="Year"><select value={selectedYear} onChange={e=>setSelectedYear(e.target.value)}>{availableYears.map(y=><option key={y}>{y}</option>)}</select></Field></div>}{dashboardPeriod==='custom'&&<div className="filter-controls custom-range"><Field label="From"><input type="date" value={customStartDate} onChange={e=>setCustomStartDate(e.target.value)}/></Field><Field label="To"><input type="date" min={customStartDate||undefined} value={customEndDate} onChange={e=>setCustomEndDate(e.target.value)}/></Field></div>}</section>
    <section className="cards six"><Card title="Overall efficiency" value={stats.efficiency?`${stats.efficiency.toFixed(2)} km/kWh`:'—'}/><Card title="Distance tracked" value={`${stats.distance.toFixed(2)} km`}/><Card title="Charging spend" value={`${settings.currency} ${stats.cost.toFixed(2)}`}/><Card title="Cost / km" value={stats.costPerKm?`${settings.currency} ${stats.costPerKm.toFixed(2)}`:'—'}/><Card title="Total energy charged" value={`${stats.charged.toFixed(2)} kWh`}/><Card title={`Average ${settings.currency}/kWh`} value={stats.avgCost?`${settings.currency} ${stats.avgCost.toFixed(2)}`:'—'}/></section>
    <section className="panel"><h2>Charging breakdown by connector</h2><div className="connector-grid">{['AC','DC'].map(t=><div className="connector-card" key={t}><strong>{t}</strong><span>{stats.breakdown[t].energy.toFixed(2)} kWh</span><span>{settings.currency} {stats.breakdown[t].cost.toFixed(2)}</span><span>{stats.breakdown[t].energy?`${settings.currency} ${(stats.breakdown[t].cost/stats.breakdown[t].energy).toFixed(2)}/kWh`:'—'}</span></div>)}</div></section>
    <section className="panel"><h2>Efficiency trend</h2>{chart.length?<ResponsiveContainer width="100%" height={320}><LineChart data={chart}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="odometer" stroke="var(--muted)" tick={{fill:'var(--muted)'}}/><YAxis stroke="var(--muted)" tick={{fill:'var(--muted)'}}/><Tooltip contentStyle={{backgroundColor:'var(--surface)',borderColor:'var(--border)',color:'var(--text)'}} labelStyle={{color:'var(--text)'}} itemStyle={{color:'var(--chart)'}} cursor={{stroke:'var(--muted)'}} formatter={value=>Number(value).toFixed(2)}/><Line type="monotone" dataKey="efficiency" stroke="var(--chart)" strokeWidth={3} dot/></LineChart></ResponsiveContainer>:<p className="muted">Add at least two charging records to calculate efficiency.</p>}</section>
    <section className="panel"><div className="panel-head"><h2>Recent charging</h2><button onClick={()=>setTab('records')}>View all</button></div><Table rows={filteredCharges.slice(0,8)} onEdit={startEdit} onDelete={deleteCharge} currency={settings.currency} timeZone={version.timezone}/></section></>}
    {tab==='add'&&<section className="panel form-panel"><div className="panel-head"><h2>{editingId?'Edit charging session':'Record charging session'}</h2>{editingId&&<button onClick={cancelEdit}>Cancel edit</button>}</div><form onSubmit={submit}><Field label="Charging date/time"><input type="datetime-local" value={form.charged_at} onChange={e=>setForm({...form,charged_at:e.target.value})} required/></Field><Field label="Connector type"><select value={form.connector_type} onChange={e=>setForm({...form,connector_type:e.target.value})} required><option value="">Select type</option><option value="AC">AC</option><option value="DC">DC</option></select></Field><Field label="Odometer (km)"><input type="number" step="1" min="0" value={form.odometer_km} onChange={e=>setForm({...form,odometer_km:e.target.value})} required/></Field><div className="grid2"><Field label="SOC before (%)"><input type="number" min="0" max="100" step="1" value={form.soc_before} onChange={e=>setForm({...form,soc_before:e.target.value})} required/></Field><Field label="SOC after (%)"><input type="number" min="0" max="100" step="1" value={form.soc_after} onChange={e=>setForm({...form,soc_after:e.target.value})} required/></Field><Field label="Energy charged (kWh)"><input type="number" step="0.01" min="0.01" value={form.kwh_charged} onChange={e=>setForm({...form,kwh_charged:e.target.value})} required/></Field><Field label={`Amount paid (${settings.currency})`}><input type="number" step="0.01" min="0" value={form.amount_paid} onChange={e=>setForm({...form,amount_paid:e.target.value})} required/></Field></div><Field label="Charging provider"><select value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}><option value="">Select provider</option>{providers.map(p=><option key={p.id} value={p.name}>{p.name}</option>)}</select></Field><Field label="Location"><input list="location-history" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><datalist id="location-history">{locationSuggestions.map(x=><option key={x} value={x}/>)}</datalist></Field><Field label="Notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="form-actions"><button className="primary" type="submit">{editingId?'Save changes':'Save charging session'}</button>{editingId&&<button type="button" onClick={cancelEdit}>Cancel</button>}</div></form></section>}
    {tab==='records'&&<section className="panel"><div className="panel-head"><h2>Charging records</h2><a className="button" href="/api/export.csv">Export CSV</a></div><Table rows={charges} onEdit={startEdit} onDelete={deleteCharge} currency={settings.currency} timeZone={version.timezone}/></section>}
    {tab==='settings'&&<><section className="panel form-panel"><h2>Vehicle settings</h2>{settingsMessage&&<div className="success">{settingsMessage}</div>}<form onSubmit={saveSettings}><Field label="Vehicle name"><input value={settings.vehicle_name} onChange={e=>setSettings({...settings,vehicle_name:e.target.value})}/></Field><Field label="Usable battery capacity (kWh)"><input type="number" step="0.1" min="10.1" max="300" value={settings.usable_battery_kwh} onChange={e=>setSettings({...settings,usable_battery_kwh:e.target.value})} required/></Field><Field label="Maximum theoretical range (km)"><input type="number" step="1" min="1" value={settings.maximum_range_km} onChange={e=>setSettings({...settings,maximum_range_km:e.target.value})}/></Field><Field label="Currency"><input value={settings.currency} onChange={e=>setSettings({...settings,currency:e.target.value})}/></Field><button className="primary">Save settings</button></form></section><section className="panel form-panel"><h2>Charging Providers</h2><div className="provider-add"><input value={newProvider} onChange={e=>setNewProvider(e.target.value)} placeholder="New provider name"/><button onClick={addProvider}>Add provider</button></div><div className="provider-list">{providers.map(p=><div key={p.id}><span>{p.name}</span><div><button className="edit-link" onClick={()=>editProvider(p)}>Edit</button><button className="danger-link" onClick={()=>removeProvider(p)}>Remove</button></div></div>)}</div></section></>}
    <footer>EV Efficiency Tracker v{version.version}{version.build_sha&&version.build_sha!=='unknown'?` · ${version.build_sha.slice(0,7)}`:''}</footer>
  </div>
}
function Card({title,value}){return <div className="card"><div className="muted">{title}</div><strong>{value}</strong></div>}
function Field({label,children}){return <label><span>{label}</span>{children}</label>}
function Table({rows,onEdit,onDelete,currency,timeZone}){if(!rows.length)return <p className="muted">No charging records yet.</p>;return <div className="table-wrap"><table><thead><tr>{['Date','Type','Odo','SOC','kWh','Cost',`${currency}/kWh`,'Provider','Location','Efficiency (km/kWh)','Efficiency (%)','Cost/km','Actions'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{inTimeZone(new Date(r.charged_at),timeZone).replace('T',' ')}</td><td>{r.connector_type||'—'}</td><td>{r.odometer_km.toFixed(2)}</td><td>{r.soc_before}% → {r.soc_after}%</td><td>{r.kwh_charged.toFixed(2)}</td><td>{currency} {r.amount_paid.toFixed(2)}</td><td>{r.charging_cost_per_kwh?`${currency} ${r.charging_cost_per_kwh.toFixed(2)}`:'—'}</td><td>{r.provider||'—'}</td><td>{r.location||'—'}</td><td>{r.efficiency_km_per_kwh?r.efficiency_km_per_kwh.toFixed(2):'—'}</td><td>{r.efficiency_percent?`${r.efficiency_percent.toFixed(2)}%`:'—'}</td><td>{r.charging_cost_per_km?`${currency} ${r.charging_cost_per_km.toFixed(2)}`:'—'}</td><td><div className="row-actions"><button className="edit-link" onClick={()=>onEdit(r)}>Edit</button><button className="danger-link" onClick={()=>onDelete(r.id)}>Delete</button></div></td></tr>)}</tbody></table></div>}
createRoot(document.getElementById('root')).render(<App/>)

